openapi: 3.0.1
info:
  title: UdaConnect Connection API
  version: 0.1.0
servers:
  - url: /
tags:
  - name: UdaConnect Connection API
    description: Connections via geolocation.
paths:
  /api/connections/{person_id}:
    get:
      tags:
        - UdaConnect Connection API
      operationId: get_connection_data_resource
      parameters:
        - name: distance
          in: query
          description: Proximity to a given user in meters
          schema:
            type: string
        - name: end_date
          in: query
          description: Upper bound of date range
          schema:
            type: string
        - name: start_date
          in: query
          description: Lower bound of date range
          schema:
            type: string
        - name: person_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content: {}
components:
  responses:
    MaskError:
      description: When any error occurs on mask
      content: {}
    ParseError:
      description: When a mask can't be parsed
      content: {}
